version: "3.8"

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=niro.dev.01@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - web

  guestbook:
    image: ghcr.io/niro58/mailer-go:${GIT_COMMIT_HASH:-prod}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.guestbook-ratelimit.ratelimit.average=20"
      - "traefik.http.routers.guestbook.rule=Host(`api.nichita-r.com`) && !Method(`POST`)"
      - "traefik.http.services.guestbook.loadbalancer.server.port=8085"
      - "traefik.http.routers.guestbook.entrypoints=websecure"
      - "traefik.http.routers.guestbook.tls.certresolver=myresolver"
      - "traefik.http.routers.guestbook.middlewares=guestbook-ratelimit"
      # Define separate router for POST methods
      - "traefik.http.middlewares.guestbook-ratelimit-post.ratelimit.average=1"
      - "traefik.http.middlewares.guestbook-ratelimit-post.ratelimit.period=1m"
      - "traefik.http.routers.guestbook-post.rule=Host(`api.nichita-r.com`) && Method(`POST`)"
      - "traefik.http.routers.guestbook-post.middlewares=guestbook-ratelimit-post"
      - "traefik.http.routers.guestbook-post.entrypoints=websecure"
      - "traefik.http.routers.guestbook-post.tls.certresolver=myresolver"
    secrets:
      - api-auth
    environment:
      - API_AUTH=/run/secrets/api-auth
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    networks:
      - web

volumes:
  letsencrypt:
    driver: local

secrets:
  api-auth:
    external: true
  clients-path:
    external: true

networks:
  web:
    external: true
