version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - web

  mailer-go:
    image: ghcr.io/niro58/mailer-go:prod
    volumes:
      - /home/niro/mailer-go/clients.json:/clients.json
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      - "traefik.http.routers.mailer-go.rule=Host(`api.nichita-r.com`)" # Route based on host
      - "traefik.http.routers.mailer-go.entrypoints=websecure" # Use the HTTPS entry point
      - "traefik.http.routers.mailer-go.tls.certresolver=myresolver" # Use Let's Encrypt for TLS
      - "traefik.http.services.mailer-go.loadbalancer.server.port=8085" # Specify the app's port (adjust if needed)
      - "traefik.http.services.mailer-go.loadbalancer.sticky=true" # Enable session stickiness
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - env
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement: {}
    networks:
      - web

networks:
  web:
    external: true
