version: "3.8"

services:
  mailer-go:
    image: ghcr.io/niro58/mailer-go:prod
    configs:
      - source: mailer-go-clients-prod
        target: /app/config/clients.json
    volumes:
      - type: bind
        source: /home/niro/mailer-go/templates
        target: /app/config/templates
        read_only: true
    environment:
      - CONFIG_PATH=/app/config/clients.json
      - TEMPLATES_PATH=/app/config/templates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailer-go.rule=Host(`api.nichita-r.com`)"
      - "traefik.http.routers.mailer-go.entrypoints=websecure"
      - "traefik.http.routers.mailer-go.tls.certresolver=myresolver"
      - "traefik.http.services.mailer-go.loadbalancer.server.port=8085"
      - "traefik.http.services.mailer-go.loadbalancer.sticky=true"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first

configs:
  mailer-go-clients-prod:
    external: true

networks:
  web:
    external: true
