name: Deploy to Server

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  commit-hash:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get_commit.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit hash
        id: get_commit
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x" # Update to the correct Go version
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...

  build-and-push-image:
    needs:
      - build-and-test
      - commit-hash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/niro58/mailer-go:${{ needs.commit-hash.outputs.commit_hash }}
            ghcr.io/niro58/mailer-go:prod

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
      - commit-hash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ needs.commit-hash.outputs.commit_hash }}" >> env
          echo "API_AUTH=$(cat secrets/api-auth.txt)" >> env
          echo "CLIENTS_PATH=$(cat secrets/clients-path.txt)" >> env

      - name: Deploy Main Project
        uses: appleboy/ssh-action@master
        with:
          host: api.nichita-r.com
          username: niro
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ~/mailer-go
            git pull origin main
            docker compose pull --ignore-pull-failures
            docker compose up -d --scale mailer-go=3 --force-recreate
